export const ACCOUNT_SET_PROFILE = "ACCOUNT_SET_PROFILE"
export const ACCOUNT_SET_TOKEN = "ACCOUNT_SET_TOKEN"
export const ACCOUNT_REMOVE_TOKEN = "ACCOUNT_REMOVE_TOKEN"
export const ACCOUNT_UPDATE_PROFILE = "ACCOUNT_UPDATE_PROFILE"