export const COMMON_SET_LOADING = "COMMON_SET_LOADING"
export const COMMON_SET_SERVER_ERRORS = "COMMON_SET_SERVER_ERRORS"
export const COMMON_ADD_BREADCRUMB = "COMMON_ADD_BREADCRUMB"
export const COMMON_CLEAR_BREADCRUMB = "COMMON_CLEAR_BREADCRUMB"
export const COMMON_UPDATE_LOGOUT_TIMEOUT = "COMMON_UPDATE_LOGOUT_TIMER"
export const COMMON_LOGOUT_TIMER_START = "COMMON_LOGOUT_TIMER_START"

